challenges:
  lava-challenge:
    active: false
  random-mob-challenge:
    active: false
    spawn-time-lower-bound: 60
    spawn-time-upper-bound: 120
timer:
  stop-timer-on-death: true
  time: 0
  save-time-between-sessions: true