name: ChallengePlugin
version: '${project.version}'
main: tgz39.challengeplugin.Main
api-version: '1.20'
authors: [TgZ39, ImReady]
commands:
  settings:
    description: Open settings for Challenges.
  timer:
    description: Controls the Timer.
